Initial commit of contribution guidelines
Wookey-Technologies/magna-carta pull request #9
Opened 2022-11-13 20:45 UTC by 3MUl0R

This is an initial commit of contribution guidelines.  A template has also been added for pull requests to go along with guideline suggestions.

2022-11-13 21:19 UTC, olympusMonspeacebeuponhim commented
yeah i dont get what any of that means

2022-11-13 21:21 UTC, 3MUl0R commented
It's a just help document essentially.

2022-11-13 21:32 UTC, TheDormouse approved these changes
LGTM - The PR template will help quite a bit.

2022-11-13 21:36 UTC, AnuAmun commented
#9 guideline needs to be replaced with tutorial

2022-11-13 21:38 UTC, TheDormouse commented
> #9 guideline needs to be replaced with tutorial

I think guidelines makes more sense for this, since this is the criteria that would need to be met in order for your PR to be accepted

2022-11-13 21:40 UTC, 3MUl0R commented
Resolves #4

2022-11-13 21:44 UTC, AnuAmun commented
#9 nope it should be a GUIDE not a RULE - Pirates of the Carrabean - the code it's like guidelines not actual rules ---- RULES are Rules - guidelines are suggestions

2022-11-14 18:19 UTC, onexdata requested changes
2 tiny grammar changes.

2022-11-14 18:19 UTC, onexdata commented on CONTRIBUTING.md
> +> Incase you missed it, you do not need to know how to make a PR to contribute. Opening a Discussion or an Issue will allow the community to help decide on the best action and someone else can do the
Incase-->In case?

2022-11-14 18:19 UTC, onexdata commented on CONTRIBUTING.md
> +If you spot a problem in the Magna Carta documents you should first search if an [issue](https://github.com/Wookey-Technologies/magna-carta/issues) or relevant [discussion](https://github.com/3MUl0R/
Comma after "Magna Carta documents"?

2022-11-14 18:26 UTC, onexdata commented
> #9 nope it should be a GUIDE not a RULE - Pirates of the Carrabean - the code it's like guidelines not actual rules ---- RULES are Rules - guidelines are suggestions

Can you clarify your comment? Are you saying we should change the term "guideline" to "tutorial", or we should make a tutorial?

2022-11-15 19:23 UTC, merged